
version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: smarthr/circleci-base
        environment:
          RAILS_ENV: test
          REDIS_HOST: 127.0.0.1
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
      - image: redis
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load --trace

      # Run test
      - run:
          command: bundle exec rake test
          when: always

