
version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/twitter-app
    docker:
      - image: smarthr/circleci-base
        environment:
          RAILS_ENV: test
          REDIS_HOST: 127.0.0.1
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: twitter-app-user
          POSTGRES_DB: twitter-app
          POSTGRES_PASSWORD: ""
      - image: redis:4.0.7
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle install

